---
title: "Uso Avanzado de Sistemas de Información Geográfica (SIG) (IMSD1025)"
subtitle: "Ing. en Medio Ambiente Y Sustentabilidad"
author: "Dr. Francisco Zambrano"
lang: es
theme: default
format:
  html:
    number-sections: true
    number-depth: 2
    smooth-scroll: true
    code-fold: true
    toc: true
    html-math-method: katex
---

## Reseña

En este repositorio se pone a disposición de los alumnos de Ing. en Medio Ambiente y Sustentabilidad de la UMayor, las clases, laboratorios y material que se utilizará en la asignatura de SIG Avanzado. Este repositorio está creado con [quarto](https://quarto.org/) por medio del software `R`.

## Clases

I) Unidad 1:Introducción al uso de R.
    
    1) [Presentación curso](Clase1/slides_clase11.html)  
    2) [Introducción a `R`](Clase1/slides_clase12.html)   
    3) [Tipos y estructuras de datos](Clase1/slides_clase13.html)
    4) [Manipulación de datos](Clase2/slides_clase21.html)
II) Unidad 2: Manejo de datos espaciales en R
    5) [Introducción al análisis espacial con R](Clase3/slides_clase31.html)
    6) [Datos Espaciales en R](Clase3/slides_clase32.html)
    7) [Sistemas de Referencia de Coordenadas (SRC)](Clase4/slides_SRC.html) 
    8) [Operaciones Geométricas con datos vectoriales](Clase4/slides_operaciones_vectoriales.html)
<!-- 9) [Maipulación de datos raster](Clase5/slides_manipulacion_rasters.html) -->
<!--     10) [Creación de mapas con {tmap}](Clase6/slides_mapas_con_tmap.html) -->
    
## Talleres

1) [Taller 1: Tipos y estructuras de datos en R](Talleres/Taller1_v2/Ejercicios_R-base.html)
2) [Taller 2: Tipos y estructuras de datos en R](Talleres/Taller2_2023/taller2_rbase.html)
3) [Taller 3: Manipulación de datos en R](Talleres/taller3_2024/taller3.html)
4) [Taller 4: Manejo de datos vectoriales con {sf}](Talleres/taller4_2024/taller4.html)
5) [Taller 5: Manejo de datos raster con {terra}](Talleres/taller5_2024/taller5.html)
6) [Taller 6: Operaciones geométricas con {sf}](Talleres/taller6_2024/taller6.html)
7) [Taller 7: Operaciones geométricas con {sf}](Talleres/Taller7_2024/taller7.html)

## Proyecto Final (20%)

<!-- - [Preparación de datos para MDE](proyecto_final/proyecto_final.html) -->

<!-- 
2) [Taller 2: Datos climáticos en R](Talleres/Taller2/Taller2.html)
3) [Taller 3: Datos vectoriales con {sf}](Talleres/Taller3/Taller3.html)
4) [Taller 4: Operaciones geométricas con {sf}](Talleres/Taller4/Taller4.html)
5) [Taller 5: Datos raster con {terra}](Talleres/Taller5/Taller5.html)
6) [Taller 6: Creación de mapas con {tmap}](Talleres/Taller6/Taller6.html)
7) [Taller recuperativo: R como SIG](Talleres/Taller_recuperativo/Taller_recuperativo.html)
-->

## Evaluaciones

<!-- 1) Evaluación 1: -->
<!--     + [Solución](Evaluaciones/Eva1_2023/evaluacion1.html) -->
<!--     + [Tipo 1](Evaluaciones/Eva1_2023/evaluacion1_forma1.html) -->
<!--     + [Tipo 2](Evaluaciones/Eva1_2023/evaluacion1_forma2.html) -->
<!--     + [Tipo 3](Evaluaciones/Eva1_2023/evaluacion1_forma3.html) -->
<!--     + [Tipo 4](Evaluaciones/Eva1_2023/evaluacion1_forma4.html) -->
<!--     + [Tipo 5](Evaluaciones/Eva1_2023/evaluacion1_forma5.html) -->
<!-- 2) [Evaluación 2](Evaluaciones/Eva2_2023/Eva2.html) -->
<!-- 3) [Evaluación recuperativa](Evaluaciones/Eva_recu_2023/Eva_recu.html) -->
<!-- 4) [Examen](Evaluaciones/Examen_2023/examen.html) -->

## Material

- R
  - [SWIRL](https://swirlstats.com/)
  - [Quick-R](https://www.statmethods.net/)

- R-Spatial
  - [r-spatial](https://www.r-spatial.org/) - Edzer Pebesma
  - [rspatial](https://www.rspatial.org/) - Robert Hijmans

- Libros R-Spatial
  - [Applied Spatial Data Analysis with R. Roger Bivand, Edzer Pebesma, Virgilio Gómez-Rubio.](http://gis.humboldt.edu/OLM/r/Spatial%20Analysis%20With%20R.pdf)
  - [Geocomputation with R. Robin Lovelace, Jakub Nowosad, Jannes Muenchow](https://geocompr.robinlovelace.net/)
  - [Spatial Data Science](https://keen-swartz-3146c4.netlify.app/). Edzer Pebesma y Roger Bivand. Estado: en desarrollo
  

